import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Link from 'next/link'

export default function ServerSidePage({data}) {
    return (
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        <main className={styles.main}>
  
            <div>server side page</div>
            <div>client visit at {data}</div>
            <Link href={'/'}>
                <a>back to home</a>
            </Link>

        </main>
  
      </div>
    )
  }

export async function getServerSideProps(){
    console.log('run getServerSideProps()')
    return {props:{data:JSON.stringify(new Date())}}
}