import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Link from 'next/link'

export default function StaticPageWithData({time}) {
    return (
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        <main className={styles.main}>
  
            <div>static page only</div>
            <div>building time: {time}</div>
            <Link href={'/'}>
                <a>back to home</a>
            </Link>

        </main>
  
      </div>
    )
  }

  export async function getStaticProps(context){

    return {
        props:{time: JSON.stringify(new Date())}
    }
  }