import { useState, useEffect } from 'react'
import styles from '../../styles/Home.module.css'
import Head from 'next/head'
import Link from 'next/link'

export default function ClientSide() {
    const [data, setData] = useState(null)
    const [isLoading, setLoading] = useState(false)
  
    useEffect(() => {
      setLoading(true)
      fetch('/api/hello')
        .then((res) => res.json())
        .then((data) => {
          setData(data)
          setLoading(false)
        })
    }, [])
  
    if (isLoading) return <p>Loading...</p>
    if (!data) return <p>No profile data</p>
  
    return (
        <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        <main className={styles.main}>  
            
            <div>
                <div>client side get name: {data.name}</div>
                <div>client side get bio: {data.bio}</div>
            </div>
            <Link href={'/'}>
                <a>back to home</a>
            </Link>

        </main>
  
      </div>
      
    )
  }