import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>home</div>
        <Link href={'/about'}>
          <a>goto about</a>
        </Link>
        <Link href={'/statics/static_page'}>
          <a>goto static page</a>
        </Link>
        <Link href={'/statics/static_page_data'}>
          <a>goto static page with data at building time</a>
        </Link>
        <Link href={'/static_paths/one'}>
          <a>goto static page by dynamic path of: one</a>
        </Link>
        <Link href={'/static_paths/two'}>
          <a>goto static page by dynamic path of: two</a>
        </Link>
        <Link href={'/static_paths/three'}>
          <a>goto static page by dynamic path of: three</a>
        </Link>
        <Link href={'/server_side/server_side_page'}>
          <a>goto server side page</a>
        </Link>
        <Link href={'/server_side_paths/abc'}>
          <a>goto server side by dynamic path of: abc</a>
        </Link>
        <Link href={'/server_side_paths/123'}>
          <a>goto server side by dynamic path of: 123</a>
        </Link>
        <Link href={'/client_side/client_side'}>
          <a>goto client side</a>
        </Link>
        <Link href={'/client_side/client_side_swr'}>
          <a>goto client side swr</a>
        </Link>
      </main>

    </div>
  )
}
